namespace: metallb-system

resources:
  - namespace.yml
  - configmap.yml
  - https://raw.githubusercontent.com/google/metallb/v0.9.5/manifests/metallb.yaml

secretGenerator:
- name: memberlist
  literals:
    - secretkey=cyWQ9E4Rw5P0rB4OkFkSQdw/DRRfU2awvz1OhwdSa5UgULTeG2sBmGKbd9SZxwbKh6VrKANqxZbpzDjTS+EeTs2XoFv2rREUAjYpnWkFlsYNfBkE4clXJJVrcgA+AgI5dTeTOmtoA/14vwVm/Z4Q1NMFV0a2vkhbCqReO1tQ4Rw=

generatorOptions:
 disableNameSuffixHash: true